[Mars] 도움말과 앱의 첫 실행시 Onboarding 적용
AppleDeveloperAcademy-MC3/Alright pull request #27
Opened 2024-08-09 10:09 UTC by SANGDOLEE

## 📓 Overview
- 앱의 첫 실행시 등장하는 OnboardingView를 추가하고 적용하였습니다. 
- SelectionView에 도움말 버튼을 추가하고, OnboardingView를 언제든지 볼 수 있게 하였습니다.
    ---> 2개의 AppStorage Bool 변수로 각각 관리합니다.
- FeedbackView 내에 물음표 버튼을 느낌표 버튼으로 변경하였습니다.

## 🤔 고민 내용
- 온보딩 뷰를 처음에는 피그마에 있는 디자인대로 모두 직접 구현하려고 했었는데, 온보딩 뷰 디자인을 보면 VStack이 총 2개로 나뉘어져있다고 생각했습니다. 근데 피그마에는 시뮬레이터 Image가 하단영역 밑으로 겹쳐들어가있어서 잘려진 Image를 사용해야하나 하는데 딱히 그런 이미지를 주지도 않았고, 3번째 온보딩화면에는 화살표랑 이것저것 들어가길래 상단부분을 그냥 Image 통째로 넣었습니다 !  윗부분은 액션도 없는 온보딩 화면 그 자체라 문제될게없어보여서 이렇게 했는데 괜찮은거겠죠 ? ㅋㅋ😅😁

- 온보딩 페이지가 총 4개인데, 처음에 구현 할 때는 각 화면마다 View 파일을 하나씩 생성하고, 각 파일 내에서 모두 각각의 뷰들을 만들었었습니다.
```swift
TabView(selection: $selectedPage) {
     FirstOnboardingPageView()
          .tag(0)
                    
     SecondOnboardingPageView()
          .tag(1)
                    
     ThirdOnboardingPageView()
          .tag(2)
                    
     FourthOnboardingPageView(isFirstLaunching: $isFirstLaunching)
          .tag(3)
}
```
이런 구조였는데,
사실 마지막 페이지를 제외하고는 나머지 3개화면 구조가 완전히 똑같으니
CommonView와 LastView 2개로만 나누고, 온보딩 메인 페이지에서 파라미터를 전달하면서 조금 더 단순하게 구조를 변경했다고 생각하는데 (?) , 제 생각이 맞던것일지 ?! 아니면 더 좋은 의견 생각나는거 있으시면 코멘트 부탁드립니다 ~ !! 😀😀

## 📸 Screenshot
<img src="https://github.com/user-attachments/assets/65973f7e-cb2d-4f05-9e8a-e0bb231bb974" width="200px;">

2024-08-10 07:32 UTC, yoondj98 requested changes
마스~~ 온보딩 View 구현하느라 고생하셨습니다..!! 👍🏻🥹👍🏻

이번 Review에서는 전반적으로 View를 조금 더 간결하게 만드는 데에 의의를 두고 진행했습니다.
확인해보시고 이해가 어려우시거나 Align이 안되는 부분이 있다면 바로 연락주시면 감사드리겠습니다! ㅎㅎ

너무 수고 많으셨어요~!!😃😃

2024-08-10 07:32 UTC, yoondj98 commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +                            .font(.system(size: 17, weight: .regular))
이 부분 폰트 적용해둔거 그대로 가져다가 쓰시면 될 것 같습니다~!

2024-08-10 07:32 UTC, yoondj98 commented on Alright/Alright/Source/View/Onboarding/OnboardingLastPageView.swift
> +    @Binding var isCompletedOnboarding: Bool
isFirstOnboarding과 isCompletedOnboarding의 용도가 겹치는 듯합니다!
변수명을 isOnboardingSheetShown과 같이 두고서,
하나로 합쳐서 사용하면 좋지 않을까 싶습니다~ 😄 😄 

간단하게 로직을 둬도 괜찮은 부분이라고 생각이 들어요!
isOnboardingSheetShown에 대해서
- [도움말] 버튼은 이걸 true로 바꾸는 로직
- [확인했어요] 버튼은 이걸 false로 바꾸는 로직을 들고 있으면 되고

1. App구동 시엔 Appstorage에서 isCompletedOnboarding값을 확인.
2. false이면 isOnboardingSheetShown을 true처리.
3. 이와 함께 바로 isCompletedOnboarding을 true로 변경.

이렇게 했을 때 얻는 효과
1. 굳이 확인했어요까지 isCompletedOnboarding 값이 전달되지 않아도 됨.
2. OnboardingView를 commonPage, lastPage로 나누지 않고 하나로 구현할 수 있음.
3. TabView내에서 Foreach로 바꿔서 View 구현 + OnboardingView에 들어갈 ViewModel 설정. (이렇게 구현하는 건 가독성 면에선 꼭 좋지만은 않을 것 같긴 합니다. ㅎㅎ)

이렇게 하면 조금 더 깔끔하게 구현할 수 있지 않을까 싶습니다 😄😄

2024-08-10 07:32 UTC, yoondj98 commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
만약 [확인했어요] 버튼이 있는 마지막 View까지 확인하지 않았으면 다음에도 다시 띄워주는 로직을 구현하려면 이 부분을 변수 전달이 아닌 전역적 접근을 하위 View에서 알아서 하는게 낫지 않을까 싶습니다!

목적은 OnboardingView를 하나로 줄이고자 함에 있습니다~!!

또한, 온보딩 과정을 모두 확인하지 않았는데 확인했다고 뜨게 되는 Route는
[SKIP]을 클릭한 경우밖에 없는데, 통상적으로 [SKIP]을 눌렀다는 건 OnBoarding에 대한 필요성 부재에 있기에 [확인했어요] 버튼이 아닌 SKIP을 누르더라도 다 본 것으로 간주하는 것이 좋을 것 같다는 의견 첨언해봅니다!

2024-08-10 11:19 UTC, SANGDOLEE commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
음. 뭔가 이해가 약간 안되는 부분이 있는데, 피그마 디자인을 보면 
 1. 앱의 첫 실행시 등장하는 온보딩 -> 마지막 뷰 버튼 이름이 "Alright 시작하기"
 2. 앱의 첫 실행 이후, 메인뷰에서 도움말버튼으로 열람하는 온보딩 -> 마지막 뷰 버튼 이름이 "확인했어요"

라서, isFirstOnboarding 변수 하나로 먼저 앱의 첫 실행에만 온보딩을 띄울 수 있게, true값이었다가 온보딩을 skip하든 alright시작하기를 누르게되든 어쨋거나 false로 변경하면서 1번의 경우에만 사용을 하고 끝.
그리고 2번의 경우까지 생각했을 때 어쨋든 같은 온보딩을 쓰는것이니까, 도움말 버튼을 누르면 기존 앱 첫실행시 사용했던 Bool변수를 true로 변경하면서 온보딩을 재차 띄우는데, 문제는 이게 앱의 첫실행으로 동작하는 온보딩인지, 도움말을 터치하여 들어온 온보딩인지 구분하기 위해 사용했던것이 isCompletedOnboarding 값이었습니다. 두개의 값을 판단해서 버튼의 Text를 확인했습니다 or Alright 시작하기 였던것이죠. 

제라스도 이렇게 이해한게 맞을까요 ? 🥹

2024-08-10 11:53 UTC, yoondj98 commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
아하! 제가 의도를 완전히 파악하지 못했었네요...!
디자인에 대한 파악을 제대로 못한 온전히 제 실수입니다~~!! 😅😅
그런 의도였다면 현재 로직도 충분히 이해가 되네요!👍🏻😄👍🏻

일단 이 상황에서 2가지 부분을 나눠서 의견을 드려보고 싶습니다!

### 1. 확인했어요 vs Alright 시작하기 의 구분

**"이게 앱의 첫실행으로 동작하는 온보딩인지, 도움말을 터치하여 들어온 온보딩인지 구분하기 위해 사용했던것이 isCompletedOnboarding 값"** 라는 말씀을 주셨는데 
사실 **'도움말을 터치하여 들어오는 온보딩'**은 어떤 과정에서든 앱의 첫 실행이 아닐 겁니다. 
이와 마찬가지로 **'Alright 시작하기'** 버튼이 뜨는 온보딩도 무조건 앱의 첫 실행일 겁니다.
그렇기에 앱이 첫실행인지 아닌지만으로도 이 두 경우를 구분할 수 있을 듯합니다.

그렇다면 꼭 isCompletedOnboarding이란 값이 없어도 isFirstOnboarding으로 구분이 가능할 듯 합니다~!!

### 2. 어느 타이밍에 isFirstOnboarding을 false처리?

이 부분은 상단에 제가 Review comment 남긴 것이 틀린 부분이라 정정드리고자 말씀을 드려봅니다!
일단 이 상황이라면 **[SKIP]**, **[Alright 시작하기]** 버튼에만 isFirstOnboarding을 false처리하는 로직을 넣어주면 될 것 같습니다.

### 3. CommonPageView와 LastPageView의 구분

사실 가장 궁금한 부분은 CommonPageView와 LastPageView를 나누게 된 계기가 어떤 부분 때문인지 궁금합니다~!
제가 코드를 보고서 생각이 든 바로는 isCompletedOnboarding과 isFirstOnboarding을 전달해서 확인했어요||Alright 시작하기 버튼은 만들고자 한 부분 정도로 이해를 했거든요~!!

그래서 제 생각엔 AppStorage가 전역이란 장점을 활용해서 두 형태의 View를 하나로 합침으로써 boiler plate 코드를 조금 더 간결하게 구현할 수 있지 않을까 싶어서 제안을 드리고 싶어요~~! 🙏🏻 🥹 🙏🏻

2024-08-10 14:34 UTC, SANGDOLEE commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
아 넵 !
일단 2번에 관해서 [SKIP], [Alight 시작하기] 버튼에만 isFirstOnboarding을 false처리하는 것은 완료가 되었습니다. 👍

그리고 3번은 ..
네 사실 '버튼'하나의 차이가 맞긴 맞습니다. 근데 이제, 4장의 온보딩 화면중에서 마지막 화면에만 버튼이 있는 형태잖아요 ? 만약 제라스의 의견대로 온보딩 페이지를 하나로 합쳐서 CommonPageView 1개만 사용한다고 해보겠습니다.

Button을 같이 생성해놓고 AppOnboardingView에서 현재 페이지를 넘겨주면서, 현재 페이지에 따라 Button에 opacity를 적용해서 마지막 페이지일때만 보여주려고 했었습니다. 근데 이렇게 하니 3번째 온보딩화면에서 4번째로 천천히 슬라이드하면 화면에 1/2만 지났을때 3번째 온보딩화면과 4번째 온보딩화면에 버튼이 같이 생겨서 보이더라구요. ( -> 아마 같은 OnboardingPageView를 사용하고 있으니까 ? )
다른 방법은 더 떠오르지 않아서, LastPage만 딱 구분하는게 맞다고 생각이 들었었습니다. 😁

2024-08-10 15:02 UTC, yoondj98 commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
오호~!! 그런 side effect가 있군요!!
공유 감사드립니다 ㅠㅠㅠ
그런 이유에서라면 저도 LastPageView 나누는게 맞을 것 같습니다!(아무래도 TabView를 활용하는 상황이다보니...!!)

좋은 의견 감사드립니다~!! 😀😀

2024-08-10 15:02 UTC, SANGDOLEE commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +                            .font(.system(size: 17, weight: .regular))
아하 ! 피그마에서 따로 Pretendard를 적용안해놧길래, 이렇게 했었던거같은데 적용해놓겠습니다 ~!

2024-08-10 16:12 UTC, SANGDOLEE commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
1962b1f
- Onboarding 모델 따로 빼서 적용
- ForEach로 변경 
정도 해두었고,, AppStorage변수랑 fullScreen쪽이 아직 정리가 안됐습니다 .. 😭

그리고 ForEach로 변경했는데도, 슬라이드 넘어가는 중간부터 버튼이 양쪽으로 보이는건 아직 있더라구요 .. 

이어서 해결해서 올려주시면 코드보고 이해해보겠습니다 ! 🥲

2024-08-10 19:16 UTC, SANGDOLEE commented on Alright/Alright/Source/View/Selection/SelectionView.swift
> +    @AppStorage("isCompletedOnboarding") var isCompletedOnboarding: Bool = true // 도움말 Onboarding
현재 마지막 수정된 기준으로 시뮬레이터 영상입니다. ( DispatchQueue 적용 X ) 
<img src="https://github.com/user-attachments/assets/caa6d6ba-ffa3-4287-8a42-9dca0422f4bb" width="200px;">

2024-08-11 06:13 UTC, yoondj98 approved these changes
모두 확인했습니다~~

어제 새벽까지 계속 수정 요청드리고 수정하시고를 반복했는데
구현 방식까지 계속 변경 요청드렸던 거 같아서 죄송해요 ㅠㅠㅠ

잘 반영해주시고 수용해주셔서 감사드립니다 마스~!!
수고 많으셨어요!!😄😄

2024-08-11 06:13 UTC, merged